# Generated by Django 3.0.3 on 2020-02-20 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, null=True)),
                ('res_add', models.CharField(blank=True, max_length=75, null=True)),
                ('res_city', models.CharField(blank=True, max_length=30, null=True)),
                ('res_state', models.CharField(blank=True, max_length=30, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
