# Generated by Django 3.0.3 on 2020-02-21 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORDERID', models.CharField(max_length=30, verbose_name='ORDER ID')),
                ('TXNAMOUNT', models.FloatField(verbose_name='TXN AMOUNT')),
                ('ORDERDATE', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ORDER DATE')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_order_paytm', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MID', models.CharField(max_length=20)),
                ('TXNID', models.CharField(max_length=64, verbose_name='TXN ID')),
                ('ORDERID', models.CharField(max_length=30, verbose_name='ORDER ID')),
                ('BANKTXNID', models.CharField(blank=True, max_length=64, null=True, verbose_name='BANK TXN ID')),
                ('TXNAMOUNT', models.FloatField(verbose_name='TXN AMOUNT')),
                ('CURRENCY', models.CharField(blank=True, max_length=4, null=True, verbose_name='CURRENCY')),
                ('STATUS', models.CharField(max_length=12, verbose_name='STATUS')),
                ('RESPCODE', models.IntegerField(verbose_name='RESP CODE')),
                ('RESPMSG', models.TextField(max_length=250, verbose_name='RESP MSG')),
                ('TXNDATE', models.DateTimeField(default=django.utils.timezone.now, verbose_name='TXN DATE')),
                ('GATEWAYNAME', models.CharField(blank=True, max_length=20, null=True, verbose_name='GATEWAY NAME')),
                ('BANKNAME', models.CharField(blank=True, max_length=75, null=True, verbose_name='BANK NAME')),
                ('PAYMENTMODE', models.CharField(blank=True, max_length=10, null=True, verbose_name='PAYMENT MODE')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_payment_paytm', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ORDERID', 'TXNID')},
            },
        ),
    ]
